### ISSUE TITLE
Error "Input string was not in a correct format"

### ISSUE THREAD

**Issue by iklingen** [pmattes/Wx3270-New#1]
wx3270 1.0alpha1
b3270 v4.0ga10

My workstation is
System:
* Windows 10 Enterprise, 64bit, Version 2004

Settings:
* Date & Time, Language
  * Windows Display Language: "English (United States)"
  * Related settings, Date, time & regional formatting
    * Country or Region: "Russia"
    * **Regional format, Current format "Russian (Russia)"**

When I try to start wx3270 I get the message window "Fatal Error" with text:
"Caught exception while processing back-end message: Input string was not in a correct format"

When I change the **Regional format** to "English (World)" the wx3270 starts OK.

**Comment by pmattes** [comment]
Fix is committed.
