### ISSUE TITLE
Extraneous behaviour with RControlKey (Enter) & mouse cursor focus

### ISSUE THREAD

**Issue by salva-rczero** [pmattes/Wx3270-New#14]
Hi Paul. I love x3270 and the new wx3270. But in my desktop (Win-10), wx3270 (wx3270-1.1ga6) has an annoying glitch:

Sometimes, after windows switch using ALT-TAB (or selected with the mouse on the Taskbar) to a wx3270 window, Enter key (RControl) is not recognized unless the mouse cursor is inside the 3270 Buffer area. When the mouse point to other windows, status area, scroll bars, extra space... the Enter is not recognized but any other key is working as usual. Once the mouse is moved inside the key works again. Even if the mouse is moved out before any key is pressed.

I tried to trace key event. And this is the results:

For a normal Enter key pressed:
20221230.155425.514 Got event 0x2
20221230.155425.514 ui< 
20221230.155425.514 
20221230.155425.514 Waiting for 3 events
20221230.155426.101 Got event 0x2
20221230.155426.101 ui< <run actions="Enter()" type="keymap" r-tag="async-63" />
20221230.155426.101 CB(ui)[#64] started
20221230.155426.102 CB(ui)[#64.1] IDLE -> RUNNING (child task to be pushed next)
20221230.155426.102 Macro[#64.2] IDLE -> RUNNING (fresh push)
20221230.155426.102 Macro[#64.2] RUNNING -> IDLE (about to resume)
20221230.155426.102 Macro[#64.2] running
20221230.155426.102 Macro[#64.2] IDLE -> RUNNING (executing)
20221230.155426.102 Macro[#64.2] 'Enter()'
20221230.155426.102 keymap -> Enter()
20221230.155426.102 ui> <oia field="not-undera" value="true"/>
20221230.155426.102 ui> <oia field="lock" value="twait"/>
20221230.155426.102 Keyboard lock(key_AID) +OIA_TWAIT +OIA_LOCKED
> Enter(5,1)
> 0x0   7dc540ffef
20221230.155426.103 SENT EOR
20221230.155426.103 ui> <oia field="not-undera" value="false"/>
20221230.155426.103 Macro[#64.2] RUNNING -> KBWAIT (keyboard locked)
20221230.155426.103 Waiting for 3 events or 1000 msec
20221230.155426.106 Got event 0x2
20221230.155426.106 ui< 
20221230.155426.106 
20221230.155426.106 
20221230.155426.106 
20221230.155426.106 
20221230.155426.106 
20221230.155426.106 
20221230.155426.106 lazya_flush: 16 slots
20221230.155426.106 Waiting for 3 events or 997 msec
20221230.155426.110 Got event 0x0
20221230.155426.110 Making host socket non-blocking
20221230.155426.110 net_input: NetworkEvents 0x1 READ
20221230.155426.110 Reading host socket
20221230.155426.110 Host socket read complete nr=33
< 0x0   f57a1d4040c3d6d4d4c1d5c440e4d5d9c5c3d6c7d5c9e9c5c411c47f1d4013ff
< 0x20  ef
20221230.155426.111 ui> <thumb top="0.257732" shown="0.742268" saved="1075" screen="43" back="0"/>
< EraseWrite(reset,restore) StartField(1,1)(default) ' COMMAND UNRECOGNIZED ...
... ' SetBufferAddress(4,80) StartField(default) InsertCursor(5,1)
20221230.155426.112 Keyboard unlock(do_reset) -OIA_TWAIT -OIA_LOCKED
20221230.155426.112 Keyboard lock(do_reset) +DEFERRED_UNLOCK
20221230.155426.112 Deferring keyboard unlock 350ms
20221230.155426.112 ui> <oia field="lock" value="deferred"/>
20221230.155426.112 ui> <oia field="timing" value="0.0"/>
20221230.155426.112 Host operation took 0.007001s to complete
20221230.155426.113 RCVD EOR
20221230.155426.113 lazya_flush: 42 slots
20221230.155426.113 Waiting for 3 events or 349 msec
20221230.155426.469 Got event 0x102
20221230.155426.469 Keyboard unlock(defer_unlock) -DEFERRED_UNLOCK
20221230.155426.469 ui> <oia field="timing"/>
20221230.155426.469 ui> <oia field="lock"/>
20221230.155426.469 Macro[#64.2] KBWAIT -> IDLE (about to resume)
20221230.155426.469 Macro[#64.2] running
20221230.155426.469 Macro[#64.2] complete, success
20221230.155426.469 CB(ui)[#64.1] RUNNING -> IDLE (about to resume)
20221230.155426.469 CB(ui)[#64.1] child task done, success
20221230.155426.469 ui> <run-result r-tag="async-63" success="true" time="0.367"/>
20221230.155426.469 CB(ui)[#64.1] complete, success
20221230.155426.469 CB(ui)[#64] complete
20221230.155426.469 Waiting for 3 events or 1634 msec
20221230.155426.546 Got event 0x2
20221230.155426.546 ui< 
20221230.155426.546 lazya_flush: 14 slots
20221230.155426.546 Waiting for 3 events or 1557 msec
20221230.155428.103 Got event 0x102
20221230.155428.103 ui> <stats bytes-received="3170" records-received="26" bytes-sent="159" records-sent="24"/>
20221230.155428.103 Waiting for 3 events
20221230.155428.260 Got event 0x2
20221230.155428.260 ui< 
20221230.155428.260 
20221230.155428.260 Waiting for 3 events
20221230.155428.524 Got event 0x2
20221230.155428.524 ui< 
20221230.155428.524 Waiting for 3 events

For the abnormal behaviour:
20221230.155633.087 Got event 0x2
20221230.155633.087 ui< 
20221230.155633.087 
20221230.155633.087 
20221230.155633.087 
20221230.155633.087 Waiting for 3 events

Please advise.

Thanks, salva. And have a good new year!

**Comment by salva-rczero** [comment]
Upgraded to wx3270-1.1ga7, same result.

**Comment by pmattes** [comment]
Cool bug! Thank you for the report. This is a particularly tricky part of the code, and there may be a few bugs still lurking there, unfortunately.

The fix is committed and will be in 1.1ga8. I can send you a pre-release if you need it.

**Comment by salva-rczero** [comment]
Thanks you Paul! That was really quick. Please send me the new package.

Regards, salva.

**Comment by pmattes** [comment]
Here you go:
    http://x3270.bgp.nu/download/specials/wx3270-1.1Apre8-setup.exe

**Comment by salva-rczero** [comment]
Thanks Paul, it works like a charm.

I've another question: sometime ago (13 years, how time flies!) I wrote a
patch for x3270 to improve some selection behaviour: (
https://sourceforge.net/p/x3270/feature-requests/8/). I would like to try
it again with wx3270, but, although I can write dotnet code, I'm lost with
the windows screen manipulation and the structure of wx3270. Can you give
me any clue on how to hook on selection changes and how to write to the
status line?

Thank you again for your kind assistance and long life to x3270 in this new
year!

**Comment by pmattes** [comment]
Looks like I dropped the ball on those earlier changes -- I can still take a look at those for x3270.

The main wx3270 selection logic is in the module SelectionManager.cs. OIA (status line) logic is spread around a bit more, but is mostly in the files starting with 'Oia'.
