### ISSUE TITLE
Text is selected instead of cursor changed of position when clicking too fast

### ISSUE THREAD

**Issue by ccoq** [pmattes/Wx3270-New#15]
Hello,
In some cases, when I click too fast, and my mouse cursor is slightly moving, the text is selected instead of the cursor is moved to the place I clicked. Apparently, it happens if I click a second time before the cursor has the time to move to the place of the first click.
I tried with other emulators, and it doesn't happens.
Have a nice day

**Comment by pmattes** [comment]
This was an issue in x3270 as well. I will address this shortly.

**Comment by pmattes** [comment]
This will be fixed in the next release.

**Comment by ccoq** [comment]
Thanks ! Do you know when the next release will be available ?
I am very interested in trying the corrected version.

**Comment by pmattes** [comment]
I should be able to release it tonight. The corresponding x3270 release went out Sunday.

**Comment by pmattes** [comment]
The fix is included in wx3270 1.1ga8.

**Comment by ccoq** [comment]
Thanks for the release !
