### ISSUE TITLE
Changing Crosshair/Background color needs restart to take effect. (1.2beta3)

### ISSUE THREAD

**Issue by tatzio** [pmattes/Wx3270-New#17]
On 1.2 when changing Crosshair/Background color does not take immediate effect (opposite to 1.1)
Program needs to be restarted.

**Comment by pmattes** [comment]
I see the issue with the changing the crosshair color and will commit a fix shortly, but I don't see any issue with changing the background color -- that takes effect immediately. Can you show me an example?

**Comment by tatzio** [comment]
Apologies, you are right, only crosshair color is the problem.
