### ISSUE TITLE
Window image is broken

### ISSUE THREAD

**Issue by iklingen** [pmattes/Wx3270-New#2]
When I change from a panel of one ISPF size (for example, the main ISPF menu) to an ISPF panel of a different size (e.g. S.ST or 3.4), the image on the screen becomes corrupted. See attached screenshots in the PDF file [Broken_Image_Screenshot_2020-09-09.pdf](https://github.com/pmattes/Wx3270-New/files/5194150/Broken_Image_Screenshot_2020-09-09.pdf).

If slightly change code of wx3270/MainScreen.cs ProcessUpdate(...) and update a screen complettely then this issue is fixed (off course it is too draft solution):
````C#
        /// <summary>
        /// Process a screen update.
        /// </summary>
        /// <param name="updateType">Update type.</param>
        private void ProcessUpdate(ScreenUpdateType updateType)
        {
            switch (updateType)
            {
                case ScreenUpdateType.Screen:
                    // this.ScreenNeedsDrawing("update", false);
                    this.ScreenNeedsDrawing("update", true);        // <= DRAFT FIX
                    break;
````

**Comment by pmattes** [comment]
This change effectively disables all incremental screen drawing optimizations. I will see about getting a better fix.

**Comment by pmattes** [comment]
A fix has been committed.
