### ISSUE TITLE
More text/examples on the Font tab

### ISSUE THREAD

**Issue by tatzio** [pmattes/Wx3270-New#20]
Since there is much more place on that tab, would be nice to have a preview for more formatting examples and more characters.
e.g. I'm always interested how the numbers are represented by the given font.

![image](https://github.com/pmattes/Wx3270-New/assets/106803609/e2a59962-5316-4130-81dc-738515b9e9dc)

**Comment by pmattes** [comment]
I didn't add the color samples, but I did add a block of numbers and special symbols at the bottom, in 1.2ga5.

**Comment by tatzio** [comment]
Thanks, digits were the main reason for this "issue".
