### ISSUE TITLE
The attribute byte is displayed wrong, at least when 41=F4

### ISSUE THREAD

**Issue by iklingen** [pmattes/Wx3270-New#3]
When 41 attribute is F4 (underscore) it displayed as underscore instead of just a blank.

See comparison with wc3270: [Attribute byte displaying_2020-09-14.pdf](https://github.com/pmattes/Wx3270-New/files/5217482/Attribute.byte.displaying_2020-09-14.pdf).

**Comment by pmattes** [comment]
This is a known issue in b3270 (the back-end for wx3270). The fix is checked into the x3270 tree and the corrected code will be in the next wx3270 release.
