### ISSUE TITLE
Fatal User Interface Error

### ISSUE THREAD

**Issue by Jyru-Ken** [pmattes/Wx3270-New#5]
Hello

On some Windows installations (7 to 10, Home to Pro, x86 to x84), we have sometimes this error message and the emulator refuses to start.

Could you tell us what to do to avoid it ?

Best regards.

![image](https://user-images.githubusercontent.com/2741548/155151132-8fda9f33-dcbc-4875-9215-a23eba862385.png)

**Comment by pmattes** [comment]
Fixed (I hope) in 1.0ga9.
