### ISSUE TITLE
MainScreen_Resize error

### ISSUE THREAD

**Issue by ccoq** [pmattes/Wx3270-New#8]
I have found this error. It occurs at startup and avoids using the application.
It looks like in same category that the issue #5 .
On Windows 10. 

![image](https://user-images.githubusercontent.com/60291058/200630870-68387e1c-2859-4251-9d0a-f4be971a524b.png)

It occurs after changing the zooming parameter in display parameters, it may be the source of the problem ?
Best regards

**Comment by ccoq** [comment]
On Screen Parameters, click on "Advanced setting scale" (my windows is in french)

![image](https://user-images.githubusercontent.com/60291058/200849507-7e6ee63c-11ea-4888-a14f-1d6d3eaf8404.png)

After, type "125" in the field on bottom :

![image](https://user-images.githubusercontent.com/60291058/200849774-9fdd66e1-2dbd-49ec-af02-9c44ea258b76.png)

Apply the modifications, and click on "Logout now" (in yellow) to restart the session and have the new graphical parameters applied in the system.
And you should have now the error.

**Comment by cckoyou** [comment]
error happened too in my machine(win10)

**Comment by pmattes** [comment]
Could you tell me which version of wx3270 this is happening on? I don't see these errors on Windows 11 (I don't have easy access to Windows 10 any more), no matter what I do with display scaling.

If it is happening on v1.1, could you try with v1.2?

**Comment by cckoyou** [comment]
v1.1 didn't work in win10, but I tried v1.2 just now and it worked. 
Appreciate your work to the simulator!
